import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";

const sesClient = new SESClient({
  region: process.env.AWS_REGION || "ap-south-1",
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || "",
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "",
  },
});

export interface EmergencyEmailPayload {
  emergencyLevel: "HIGH" | "CRITICAL";
  zone: string;
  riskScore: number;
  triggerFactors: string[];
  immediateActions: string[];
  evacuationZones: string[];
  safeAssemblyPoint: string;
  dgfasliRequired: boolean;
  generatedAt: Date;
}

export async function sendEmergencyAlert(payload: EmergencyEmailPayload): Promise<boolean> {
  const sender    = process.env.AWS_SES_FROM_EMAIL    || process.env.AWS_SES_SENDER_EMAIL;
  const recipient = process.env.AWS_SES_ALERT_EMAIL   || process.env.AWS_SES_RECIPIENT_EMAIL;

  if (!sender || !recipient) {
    console.warn("[SES] AWS_SES_FROM_EMAIL or AWS_SES_ALERT_EMAIL not set — skipping alert email.");
    return false;
  }

  const subject = `🚨 VIGIL ${payload.emergencyLevel} EMERGENCY — ${payload.zone.replace("_", " ")} | Risk Score: ${payload.riskScore}/100`;

  const bodyHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Inter, Arial, sans-serif; background: #f8fafc; margin: 0; padding: 24px; }
    .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; border: 1px solid #e2e8f0; }
    .header { background: ${payload.emergencyLevel === "CRITICAL" ? "#991b1b" : "#b45309"}; padding: 24px; }
    .header h1 { color: white; margin: 0; font-size: 20px; }
    .header p { color: rgba(255,255,255,0.8); margin: 4px 0 0; font-size: 13px; }
    .body { padding: 24px; }
    .kpi { display: inline-block; background: #fee2e2; border: 1px solid #fca5a5; border-radius: 8px; padding: 8px 16px; margin: 0 8px 8px 0; }
    .kpi .label { font-size: 10px; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
    .kpi .value { font-size: 20px; font-weight: 700; color: #dc2626; font-family: monospace; }
    .section { margin: 20px 0; }
    .section h3 { font-size: 13px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px; }
    .factor { padding: 6px 12px; background: #fef2f2; border-left: 3px solid #dc2626; margin: 4px 0; border-radius: 0 6px 6px 0; font-size: 13px; color: #1e293b; }
    .action { padding: 7px 0; border-bottom: 1px solid #f1f5f9; font-size: 13px; color: #1e293b; }
    .zone-badge { display: inline-block; background: #fee2e2; color: #dc2626; border: 1px solid #fca5a5; padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: 600; margin: 2px; }
    .assembly { background: #dcfce7; border: 1px solid #86efac; border-radius: 8px; padding: 12px 16px; margin-top: 8px; font-size: 13px; color: #166534; }
    .regulatory { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 12px 16px; margin-top: 12px; font-size: 12px; color: #1e40af; }
    .footer { background: #f8fafc; padding: 16px 24px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>⚠ ${payload.emergencyLevel} EMERGENCY ALERT</h1>
    <p>VIGIL Industrial Safety Intelligence · ${new Date(payload.generatedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</p>
  </div>
  <div class="body">
    <div class="kpi">
      <div class="label">Zone</div>
      <div class="value">${payload.zone.replace("_", " ")}</div>
    </div>
    <div class="kpi">
      <div class="label">Risk Score</div>
      <div class="value">${payload.riskScore}/100</div>
    </div>

    <div class="section">
      <h3>Compound Risk Factors</h3>
      ${payload.triggerFactors.map((f) => `<div class="factor">${f}</div>`).join("")}
    </div>

    <div class="section">
      <h3>Evacuation Zones</h3>
      ${payload.evacuationZones.map((z) => `<span class="zone-badge">${z.replace("_", " ")}</span>`).join("")}
      <div class="assembly">✅ Safe Assembly Point: ${payload.safeAssemblyPoint}</div>
    </div>

    <div class="section">
      <h3>Immediate Actions</h3>
      ${payload.immediateActions
        .map((a) => `<div class="action"><span style="color:#dc2626;font-weight:bold;margin-right:8px;">&#8226;</span>${a}</div>`)
        .join("")}
    </div>

    ${
      payload.dgfasliRequired
        ? `<div class="regulatory">
        ⚠ <strong>DGFASLI notification required within 4 hours</strong> — File Form 18 (Fatal Accident) or Form 19 (Dangerous Occurrence) under the Factories Act 1948.
      </div>`
        : ""
    }
  </div>
  <div class="footer">
    Generated by VIGIL Safety Intelligence Platform · Coke Oven Battery · Visakhapatnam Steel Plant
  </div>
</div>
</body>
</html>`;

  const bodyText = `VIGIL ${payload.emergencyLevel} EMERGENCY ALERT
Zone: ${payload.zone} | Risk Score: ${payload.riskScore}/100
Time: ${new Date(payload.generatedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST

TRIGGER FACTORS:
${payload.triggerFactors.map((f, i) => `${i + 1}. ${f}`).join("\n")}

EVACUATION ZONES: ${payload.evacuationZones.join(", ")}
SAFE ASSEMBLY POINT: ${payload.safeAssemblyPoint}

IMMEDIATE ACTIONS:
${payload.immediateActions.map((a, i) => `${i + 1}. ${a}`).join("\n")}

${payload.dgfasliRequired ? "⚠ DGFASLI notification required within 4 hours — Form 18/19 under Factories Act 1948" : ""}

-- VIGIL Safety Intelligence Platform`;

  try {
    await sesClient.send(
      new SendEmailCommand({
        Source: sender,
        Destination: { ToAddresses: [recipient] },
        Message: {
          Subject: { Data: subject, Charset: "UTF-8" },
          Body: {
            Html: { Data: bodyHtml, Charset: "UTF-8" },
            Text: { Data: bodyText, Charset: "UTF-8" },
          },
        },
      })
    );
    console.log(`[SES] Emergency alert sent to ${recipient}`);
    return true;
  } catch (e) {
    console.error("[SES] Failed to send alert:", e);
    return false;
  }
}
